In [0]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import *

- tf.keras.layers.RepeatVector(n) 将输入重复n次

In [0]:
feature_num = 32

In [0]:
model = Sequential()
model.add(Input(feature_num))
model.add(Dense(10))

In [0]:
x = np.random.uniform(0, 256, size=(5, feature_num))

In [0]:
out = model(x)

In [0]:
out.shape

TensorShape([5, 10])

In [0]:
model.add(RepeatVector(3))

In [0]:
out = model(x)

In [0]:
out.shape

TensorShape([5, 3, 10])

In [0]:
out[0, 1, :]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-295.49417 ,  127.20011 ,  -61.546577, -280.54214 , -103.917694,
        -33.411076,   31.143768,  355.34976 , -346.5499  ,   82.681496],
      dtype=float32)>

In [0]:
out[0, 2, :]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-295.49417 ,  127.20011 ,  -61.546577, -280.54214 , -103.917694,
        -33.411076,   31.143768,  355.34976 , -346.5499  ,   82.681496],
      dtype=float32)>

In [0]:
out[0, 1, :] == out[0, 0, :]

<tf.Tensor: shape=(10,), dtype=bool, numpy=
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])>